# Dockerfile para python_script
FROM python:3.8

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1

# COPY . .

CMD ["python3", "/usr/src/app/main.py"]
